name: unittest
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install boost
      run: sudo apt-get install libboost-dev
    - name: test
      run: cd fibonacci && sh test.sh
